UX Improvments
zkp2p/zk-p2p pull request #169
Opened 2023-11-12 14:05 UTC by justinkchen

2023-11-12 17:17 UTC, asoong requested changes
Dooooooope:
- Can you post screens, I want to see the block explorer link
- Would suggest that instead of waiting to set the transaction on success, you set it on submit so they can see it while its mining
- Put the confetti behind a feature flag

2023-11-12 17:17 UTC, asoong commented on client/src/components/ProofGen/MailTable.tsx
> +const Icon = styled(SVGIconThemed)`
I've been using `react-feather` for these. There should already be a mail icon.

2023-11-12 17:17 UTC, asoong commented on client/src/components/RegistrationForm/NewRegistration.tsx
> +  const [tx, setTx] = useState<string | null>(null);
Prefer: `[submitRegistrationTransactionHash, setSubmitRegistrationTransactionHash]` or better

2023-11-12 17:17 UTC, asoong commented on client/src/components/RegistrationForm/NewRegistration.tsx
> +    abi: rampAbi ?? undefined,
Need a better solution for the typing mismatch here. I've left all sc writes like this for now until we can address them all

2023-11-12 17:17 UTC, asoong commented on client/src/components/Swap/OnRamp.tsx
> +  const [tx, setTx] = useState<string | null>(null);
Same, see above

2023-11-12 17:17 UTC, asoong commented on client/src/components/Swap/OnRamp.tsx
> +    abi: sendProcessorAbi ?? undefined,
Is there a potential for a runtime error? If not I'd rather leave these until we address them all

2023-11-12 17:17 UTC, asoong commented on client/src/components/modals/Modal.tsx
> +            href={`https://goerli.etherscan.io/tx/${transactionAddress}`}
Can you add the block scan link to `SmartContractContext` and pull that in here?

2023-11-12 17:17 UTC, asoong commented on client/src/icons/svg/dark-mailbox.svg
Shouldn't need this!

2023-11-12 23:02 UTC, justinkchen commented
Also moved confetti on submit of "Complete Order" as sachin mentioned, they are expecting it to be "done" and may navigate away by that point just like you said, they want to see the tx on etherscan so we will show confetti right away as it is in the process of completing at that point already.

2023-11-12 23:06 UTC, justinkchen commented
https://www.dropbox.com/s/mv0vatm59my3nb4/Screen%20Recording%202023-11-13%20at%201.57.49%E2%80%AFAM.mov?dl=0

2023-11-12 23:06 UTC, justinkchen commented
> Dooooooope:
> 
> * Can you post screens, I want to see the block explorer link
> * Would suggest that instead of waiting to set the transaction on success, you set it on submit so they can see it while its mining
> * Put the confetti behind a feature flag


Screen recording:

https://www.dropbox.com/s/mv0vatm59my3nb4/Screen%20Recording%202023-11-13%20at%201.57.49%E2%80%AFAM.mov?dl=0

2023-11-13 03:01 UTC, asoong commented
LGTM

2023-11-13 03:01 UTC, asoong approved these changes

2023-11-13 03:01 UTC, merged