Added implied conversion rate to Venmo and Revolut deposit creation t…
zkp2p/zk-p2p pull request #363
Opened 2024-05-02 23:25 UTC by bweick

…able.

2024-05-02 23:56 UTC, asoong approved these changes
LGTM. Any reason not to add to UPI / Garanti?

2024-05-03 04:54 UTC, bweick commented
> LGTM. Any reason not to add to UPI / Garanti?

can def add it

2024-05-07 03:35 UTC, asoong requested changes
Looking mostly good, minor nits

2024-05-07 03:35 UTC, asoong commented on client/src/components/Swap/index.tsx
> +        return 'Send Amount Less Than Minimum';
Lower case the error string except the first word

2024-05-07 03:35 UTC, asoong commented on client/src/helpers/strings/revolut.ts
> +    No Revolut Tag details found.
Whoops meant to put `Revtag` in there, we do that everywhere for consistency

2024-05-07 03:35 UTC, asoong commented on client/src/components/Deposit/revolut/NewPosition.tsx
> +      return `Rate: ${calculateConversionRate(receiveAmountInput, depositAmountInput)} EUR/USDC`;
@richardliang heads up we'll have to address this in multi currency

2024-05-08 01:52 UTC, asoong approved these changes
LGTM

2024-05-08 01:53 UTC, merged